name: Release to PyPI
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    # environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up uv
        uses: yezz123/setup-uv@v4
      - name: Install dependencies and build
        run: uv tool --from build pyproject-build --installer uv
      #   - name: Upload artifacts
      #     uses: actions/upload-artifact@v2
      #     with:
      #       name: distributions
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
